### ISSUE TITLE
paint line color according to data

### ISSUE THREAD

**Issue by hhgsplk** [secops4thewin/force_directed_viz#3]
I don't know is this is supposed to be working already...if so, I cannot get it to work. I have 
<option name="force_directed_viz.force_directed.LineColor">enabled</option>
but the lines are not showing colors, just grey. Anything else that I need to add? (color definitions are there)

**Comment by secops4thewin** [comment]
Hey @hhgsplk sorry for the delayed response.  I responded on twitter.  This should be fixed with version 3 that I am just adding to Splunkbase
